# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
  fetchDepth: 0


- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'testdemoproject'
    organization: 'testdemoproject'
    scannerMode: 'MSBuild'
    projectKey: 'testdemoproject_testdemoproject'
    projectName: 'testdemoproject'


- task: SonarCloudAnalyze@1
  inputs:
    jdkversion: 'JAVA_HOME_17_X64'

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'